### ISSUE TITLE
Embedding blocked because configuration mode is set to 'DENY'

### ISSUE THREAD

**Issue by aldets** [sinch-contact-pro/CPC#2]
Good day,

Create job, by the way. Awesome that this has been done and looking forward to start using it.
Facing an issue though as the title says. I'm running Sinch Contact Pro FP19 On-premise. I've used the examples that have been provided here. Everything works, and scripts are loaded, but for unknown reasons "sap-ui-core.js" is loaded from this URL: [https://ui5.sap.com/1.71/resources/sap-ui-core.js](url).
Also Chrome console log shows that "embedded.html" is loaded from my server:
https://[CP_URL]/ecf/latest/communicationpanel/embedded.html?salesforce=true&responsive=true&minWidth=500&minHeight=400
But I suspect that it still loads from the cloud. Because if I look at the Source file, the console shows this:
`var frameOption = "deny"; // default
    if (whiteList && whiteList.length > 0) {
    	if (isTrustedURL()) {
	    frameOption = "allow";`
Although I have changed every "embedded.html" content to "allow" that I could find in the ECF_Agent VU directory. It still shows me every where "deny".
Opening the "../embedded.html" URL without the salesforce parameters also shows "deny".
Opening the "../embedded.html" locally in the browser in the server shows "allow"
file:///C:/SAP/ContactCenter/VU/ECF_Agent/tomcat/webapps/ecf%23latest%23cp/embedded.html

I think that this "deny" is preventing me from interacting with the loaded CP UI. It loads, but I can't login. If I define "username" and "password" in "my-web-component-wrapper-for-cpc.js", it even logs in, but again, can't do anything. I see the red circle indicating that user action is disabled.

I'm out of ideas, where have I yet to change it. I'm hosting, or atleast trying to host, everything locally (eg. sap-ui-core.js is hosted locally). Any help is much appreciated.

Kind regards,
Alder

**Comment by aldets** [comment]
Solved:
Managed to get it working. Turned out, I had some configuration missing that wasn't affecting Communication Panels regular work. I needed to define the host(s) in CPConnection.json "whitelist".
Keep up the good work, it's an awesome feature!
Alder

**Comment by cpc-dev-contactpro** [comment]
Hi @aldets happy to hear you figured it out already. For further info on the required Allowlist and CORS settings: https://docs.cc.sinch.com/onpremise/fp19/infrastructure-administrator/en/oxy_ex-1/common/ewy1616660410295.html. 
This is also briefly mentioned in the Prerequisites -section in CPC Playground. Be sure to read about other prerequisites as well.

Edit: Forgot to say that indeed the SAP UI5 library is loaded from SAP's CDN, even in our On-Prem edition. I don't have the facts but I believe there is some licencing-related question behind this, preventing us from shipping UI5 with the product. However, if you want to take manual control over it, you could download SAP UI5, host it yourself, and manually edit our index.html files to point to UI5 located on your own server. I would not recommend this though, unless your on-prem users are within a highly secured environment in a closed network without Internet access.
